# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHX49SmzqFa1b-k5chmBO3Fff8hH8CPx
"""

if True:
  print("This is my 2nd class of Python Language")

# defining variables
name = "Umar"
age = 21
nationality = "Pakistani"

print(name, "is a", age, "years old", nationality)

# input and output functions
name = input("Enter your name: ")
age = input("Enter your age: ")
nationality = input("Enter your nationality: ")

print(name, "is a", age, "years old", nationality)

# primitive data types
x = 10
y = 10.21
z = 3j

print("The real number of z is", z.real)
print("The imaginary number of z is", z.imag)

# String
sentence = "This is my 2nd class of Python Language"
print("The first letter of sentence is: ", sentence[0])
print("The last letter of sentence is: ", sentence[-9])

name = "Umar"
greeting = "Hello " + name
print(greeting)

repeat = ("\n" + greeting) * 3
print(repeat)

print(sentence[0:20])

# replace substring
print(sentence.replace("2nd", "3rd"))

# List
numbers = [1, 2, 3, 4, 5]
print(numbers)

numbers.append(6)
print(numbers)

print(numbers[0:3])

# Tupple
numbers = (1, 2, 3, 4, 5)
print(numbers)

# Set
numbers = {1, 2, 3, 4, 5}
numbers.add(5)
numbers.add(6)
print(numbers)

# Dictionary
student = {"name": "Umar", "age": 21, "nationality": "Pakistani"}
print(student)

# Implicit Conversion
num1 = 2
num2 = 2.7
result = num1 + num2
print(result)
print(type(num1))
print(type(num2))
print(type(result))

# Explicit Conversion
num1 = "20"
num2 = 27
result = int(num1) + num2
print(result)
print(type(num1))
print(type(num2))
print(type(result))

import random

sentence = "This is my 2nd class, of Python Language"
lis = sentence.split()
print(lis)

# Choice List
print(random.choice(lis))

# Shuffle List
random.shuffle(lis)
print(lis)